### PR TITLE
Fixed & updated NodeExpress request JSON outputs

### PR DESCRIPTION
**Pull request by WhistleWhileYouWork**
Please review my comments on the second commit 430e679. I may have to change the WebD address comparison to make it more efficient.

### CODE REVIEW

**Comment by IonutAlexandruPanait** [comment]
We will test those changes and if it is working we will merge your pull request. Thank you for your support.

**Comment by ibudisteanu** [comment]
You had one question how you compare the minerAddress. You can do how you have done but it is not fast thought. ".data.minerAddress.toString("hex") === address.toString("hex"))"

If you compare two buffers ussing the function called .equals

data.minerAddress.equals(address)

**Comment by ibudisteanu** [comment]
Really good job!

**Comment by WhistleWhileYouWork** [comment]
Ah yes, I tried .equals first but I was still trying to figure out the code and probably did it wrong. Thanks. I will have a couple more updates to NodeExpress soon.

**Pull request merged**
